### ISSUE TITLE
errorMessage":"Invalid regular expression: missing /"

### ISSUE THREAD

**Issue by kulrohit** [ryanray/slack-lambda-weather#1]
curl -X POST --data "token=<TOKEN>&text=95614" https://<API GATEWAY>
{"errorMessage":"Invalid regular expression: missing /","errorType":"SyntaxError","stackTrace":["Module._compile (module.js:439:25)","Object.Module._extensions..js (module.js:474:10)","Module.load (module.js:356:32)","Function.Module._load (module.js:312:12)","Module.require (module.js:364:17)","require (module.js:380:17)"]}

**Comment by ryanray** [comment]
@kulrohit do you see anything in the cloudwatch logs?

**Comment by kulrohit** [comment]
Hey Ryan,
Thanks for reply.I got it correct. It was typo from side

Thanks a lot.it worked properly now.
next I am trying is to integrate same with Alexa

**Comment by ryanray** [comment]
Awesome!
